spring:
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    database: h2
    hibernate:
      ddl-auto: none